version: '3.9'
services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
      - localstack
    environment:
      - PORT=8080
      - DB_HOST=db
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=123
      - AWS_SECRET_ACCESS_KEY=456
      - AWS_REGION=us-east-1
      - NODE_ENV=production
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=dynamo,s3
      - AWS_DEFAULT_REGION=us-east-1
      - HOSTNAME_EXTERNAL=localstack
