version: '3.9'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=lambda,s3
      - AWS_DEFAULT_REGION=us-east-1
# docker-compose up -d --remove-orphans
