on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

name: CI

jobs:
  server-ci:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: npm install

      - name: lint
        run: npm run lint

      - name: test
        run: npm run test
